//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public int idCart { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
